# fly.toml app configuration file generated for a-soldcoin-list on 2024-01-14T18:13:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "a-soldcoin-list"
primary_region = "hkg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[[mounts]]
  source = "alist_db_data"
  destination = "/opt/alist/data"
  auto_extend_size_threshold = 0

[[services]]
  protocol = "tcp"
  internal_port = 5244
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
